# C:\mediflow_workspace\settlement-service\src\main\resources\application.yml

server:
  port: 7774

spring:
  application:
    name: settlement-service

  datasource:
    url: jdbc:mysql://localhost:3306/mediflow_settlement?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: mediflow
    password: "1234"
    virtual-host: /

# Eureka 비활성화 (인프라 준비 전)
eureka:
  client:
    enabled: false

# RabbitMQ 헬스체크 비활성화 (인프라 준비 전)
management:
  health:
    rabbit:
      enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.flywaydb: info